[package]
name = "retris"
version = "0.6.2"
authors = ["Linus <linus@cosmos-ink.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libremarkable = "0.4.3"
rand = "0.7"
tetris_core = "0.2"
downcast-rs = "1.2"
fxhash = "0.2"
clap = "3.0.0-beta.1"
lazy_static = "1.4.0"
