[package]
name = "retris"
version = "0.3.1"
authors = ["Linus <linus@cosmos-ink.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7.3"
libremarkable = { git = "https://github.com/LinusCDE/libremarkable.git", rev = "254d008" }
tetris_core = "0.2.0"
downcast-rs = "1.2.0"